DROP TABLE IF EXISTS auth_sessions CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS persons CASCADE;

-- ==============
-- app_users
-- ==============
CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           username VARCHAR(64) NOT NULL UNIQUE,
                           password_hash VARCHAR(512) NOT NULL,
                           role VARCHAR(32) NOT NULL DEFAULT 'USER',

                           CONSTRAINT app_users_username_nonempty CHECK (length(username) > 0)
);

-- ==============
-- auth_sessions
-- ==============
CREATE TABLE auth_sessions (
                               token VARCHAR(64) PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               expires_at TIMESTAMP NOT NULL,

                               CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id)
                                   REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE INDEX idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX idx_auth_sessions_expires_at ON auth_sessions(expires_at);

-- ==============
-- persons
-- ==============
CREATE TABLE persons (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         eyeColor  VARCHAR(16) NULL,
                         hairColor VARCHAR(16) NULL,

                         location_x REAL NOT NULL,
                         location_y REAL NOT NULL,
                         location_z REAL NOT NULL,

                         passportID VARCHAR(35) NOT NULL,
                         nationality VARCHAR(16) NOT NULL,

                         CONSTRAINT persons_passport_id_nonempty CHECK (length(passportID) > 0)
);

-- ==============
-- events
-- ==============
CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        tickets_count INTEGER NULL,
                        eventType VARCHAR(16) NOT NULL,

                        CONSTRAINT events_name_nonempty CHECK (length(name) > 0),
                        CONSTRAINT events_tickets_count_positive CHECK (tickets_count IS NULL OR tickets_count > 0)
);

-- ==============
-- venues
-- ==============
CREATE TABLE venues (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        capacity INTEGER NOT NULL,
                        type VARCHAR(16) NOT NULL,

                        address_zip_code VARCHAR(64) NULL,

                        town_x REAL NULL,
                        town_y REAL NULL,
                        town_z REAL NULL,

                        CONSTRAINT venues_name_nonempty CHECK (length(name) > 0),
                        CONSTRAINT venues_capacity_positive CHECK (capacity > 0),
                        CONSTRAINT venues_zip_minlen CHECK (address_zip_code IS NULL OR length(address_zip_code) >= 7)
);

-- ==============
-- tickets
-- ==============
CREATE TABLE tickets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         name VARCHAR(255) NOT NULL,

                         coordinates_x INTEGER NOT NULL,
                         coordinates_y BIGINT NOT NULL,

                         creation_date DATE NOT NULL,

                         person_id BIGINT,
                         event_id  BIGINT NOT NULL,
                         venue_id  BIGINT NULL,

                         price DOUBLE PRECISION NOT NULL,
                         type VARCHAR(16) NOT NULL,
                         discount BIGINT NOT NULL,
                         number BIGINT NOT NULL,
                         comment TEXT NOT NULL,
                         refundable BOOLEAN NOT NULL DEFAULT FALSE,

                         CONSTRAINT tickets_name_nonempty CHECK (length(name) > 0),
                         CONSTRAINT tickets_coordinates_x_max CHECK (coordinates_x <= 265),
                         CONSTRAINT tickets_price_positive CHECK (price > 0),
                         CONSTRAINT tickets_discount_range CHECK (discount > 0 AND discount <= 100),
                         CONSTRAINT tickets_number_positive CHECK (number > 0),
                         CONSTRAINT tickets_comment_nonempty CHECK (length(comment) > 0),

                         CONSTRAINT fk_tickets_person FOREIGN KEY (person_id) REFERENCES persons(id),
                         CONSTRAINT fk_tickets_event  FOREIGN KEY (event_id)  REFERENCES events(id),
                         CONSTRAINT fk_tickets_venue  FOREIGN KEY (venue_id)  REFERENCES venues(id)
);

CREATE INDEX idx_tickets_person_id ON tickets(person_id);
CREATE INDEX idx_tickets_event_id  ON tickets(event_id);
CREATE INDEX idx_tickets_venue_id  ON tickets(venue_id);
