-- Incremental migration for import history feature.
-- Run this once on an existing database where import_operations does not exist.

CREATE TABLE IF NOT EXISTS import_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    imported_count INTEGER NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NULL,

    CONSTRAINT import_operations_status_values CHECK (status IN ('IN_PROGRESS', 'SUCCESS', 'FAILED')),
    CONSTRAINT import_operations_imported_count_positive CHECK (imported_count IS NULL OR imported_count > 0),
    CONSTRAINT fk_import_operations_user FOREIGN KEY (user_id)
        REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_import_operations_user_id ON import_operations(user_id);
CREATE INDEX IF NOT EXISTS idx_import_operations_status ON import_operations(status);
CREATE INDEX IF NOT EXISTS idx_import_operations_started_at ON import_operations(started_at);
